'use client';

// ═══════════════════════════════════════════════════════════════════
// Block-based note system inspired by SiYuan Note
// Rich block types with WYSIWYG editing, slash commands, backlinks
// ═══════════════════════════════════════════════════════════════════

// ── Block Types (SiYuan-inspired) ──

export type BlockType =
  | 'paragraph'     // Default text block
  | 'heading'       // H1–H6, level stored in properties.level
  | 'code'          // Fenced code block, language in properties.language
  | 'math'          // LaTeX math block
  | 'quote'         // Block quote
  | 'callout'       // Admonition/callout (info, warning, tip, etc.)
  | 'list-item'     // Unordered list item (bullet)
  | 'numbered-item' // Ordered list item
  | 'todo'          // Checkbox item, checked in properties.checked
  | 'divider'       // Horizontal rule / thematic break
  | 'image'         // Image block, src in properties.src
  | 'table'         // Table block, data in content as markdown
  | 'embed'         // Embed another block or page, ref in properties.ref
  | 'toggle'        // Toggle/collapsible heading, children hidden when collapsed

// ── Block Interface ──

export interface NoteBlock {
  id: string;
  type: BlockType;              // Block type — defaults to 'paragraph'
  content: string;              // Markdown text content
  parentId: string | null;      // null = top-level block
  pageId: string;               // Which page this block belongs to
  order: string;                // Fractional index string for ordering
  collapsed: boolean;
  indent: number;               // Nesting depth (0 = top level)
  properties: Record<string, string>; // Type-specific properties
  refs: string[];               // Page IDs referenced via [[links]]
  createdAt: number;
  updatedAt: number;
}

// ── Page Interface ──

export interface NotePage {
  id: string;
  title: string;
  name: string;                 // Lowercase normalized (for lookups)
  isJournal: boolean;
  journalDate?: string;         // YYYY-MM-DD for journal pages
  icon?: string;                // Emoji or icon key
  coverImage?: string;          // Banner image URL
  properties: Record<string, string>;
  tags: string[];
  favorite: boolean;
  pinned: boolean;
  createdAt: number;
  updatedAt: number;
}

// ── Notebook (collection of pages) ──

export interface NoteBook {
  id: string;
  title: string;
  description?: string;
  pageIds: string[];
  icon?: string;
  coverColor?: string;
  createdAt: number;
  updatedAt: number;
  autoGenerated: boolean;
  category?: string;
  chapters: NoteBookChapter[];
}

export interface NoteBookChapter {
  id: string;
  title: string;
  pageIds: string[];
  order: number;
}

// ── Bi-directional link ──

export interface PageLink {
  sourcePageId: string;
  targetPageId: string;
  sourceBlockId: string;
  context: string;
}

// ── Graph visualization ──

export interface GraphNode {
  id: string;
  label: string;
  size: number;
  color?: string;
  isJournal: boolean;
}

export interface GraphEdge {
  source: string;
  target: string;
  weight: number;
}

// ── Search ──

export interface NoteSearchResult {
  type: 'page' | 'block';
  pageId: string;
  blockId?: string;
  title: string;
  snippet: string;
  score: number;
}

// ── AI ──

export interface NoteAIState {
  isGenerating: boolean;
  targetPageId: string | null;
  targetBlockId: string | null;
  generatedText: string;
  prompt: string;
}

// ── Slash Commands ──

export interface SlashCommand {
  id: string;
  label: string;
  icon: string;
  description: string;
  category: 'insert' | 'format' | 'embed' | 'ai';
  action: string;
  blockType?: BlockType;        // Target block type for conversion commands
}

export const SLASH_COMMANDS: SlashCommand[] = [
  // ── Format ──
  { id: 'h1', label: 'Heading 1', icon: 'heading-1', description: 'Large section heading', category: 'format', action: 'heading-1', blockType: 'heading' },
  { id: 'h2', label: 'Heading 2', icon: 'heading-2', description: 'Medium section heading', category: 'format', action: 'heading-2', blockType: 'heading' },
  { id: 'h3', label: 'Heading 3', icon: 'heading-3', description: 'Small section heading', category: 'format', action: 'heading-3', blockType: 'heading' },
  { id: 'quote', label: 'Quote', icon: 'quote', description: 'Block quote', category: 'format', action: 'quote', blockType: 'quote' },
  { id: 'callout', label: 'Callout', icon: 'alert-circle', description: 'Highlighted callout box', category: 'format', action: 'callout', blockType: 'callout' },
  { id: 'toggle', label: 'Toggle', icon: 'chevron-right', description: 'Collapsible section', category: 'format', action: 'toggle', blockType: 'toggle' },
  // ── Insert ──
  { id: 'todo', label: 'To-do', icon: 'check-square', description: 'Task checkbox', category: 'insert', action: 'todo', blockType: 'todo' },
  { id: 'bullet', label: 'Bullet list', icon: 'list', description: 'Simple bullet point', category: 'insert', action: 'bullet', blockType: 'list-item' },
  { id: 'numbered', label: 'Numbered list', icon: 'list-ordered', description: 'Numbered item', category: 'insert', action: 'numbered', blockType: 'numbered-item' },
  { id: 'code', label: 'Code block', icon: 'code', description: 'Fenced code block', category: 'insert', action: 'code', blockType: 'code' },
  { id: 'math', label: 'Math block', icon: 'sigma', description: 'LaTeX math equation', category: 'insert', action: 'math', blockType: 'math' },
  { id: 'table', label: 'Table', icon: 'table', description: 'Data table', category: 'insert', action: 'table', blockType: 'table' },
  { id: 'divider', label: 'Divider', icon: 'minus', description: 'Horizontal rule', category: 'insert', action: 'divider', blockType: 'divider' },
  { id: 'image', label: 'Image', icon: 'image', description: 'Insert an image', category: 'insert', action: 'image', blockType: 'image' },
  // ── Embed ──
  { id: 'link', label: 'Page link', icon: 'link', description: 'Link to another page [[...]]', category: 'embed', action: 'page-link' },
  { id: 'embed', label: 'Embed page', icon: 'frame', description: 'Embed another page inline', category: 'embed', action: 'embed-page', blockType: 'embed' },
  // ── AI ──
  { id: 'ai-continue', label: 'AI Continue', icon: 'sparkles', description: 'AI continues writing', category: 'ai', action: 'ai-continue' },
  { id: 'ai-summarize', label: 'AI Summarize', icon: 'book-open', description: 'AI summarizes this page', category: 'ai', action: 'ai-summarize' },
  { id: 'ai-expand', label: 'AI Expand', icon: 'expand', description: 'AI expands on this block', category: 'ai', action: 'ai-expand' },
  { id: 'ai-rewrite', label: 'AI Rewrite', icon: 'pen-line', description: 'AI rewrites this block', category: 'ai', action: 'ai-rewrite' },
];

// ── Callout types ──

export const CALLOUT_TYPES = ['info', 'tip', 'warning', 'danger', 'note', 'quote'] as const;
export type CalloutType = typeof CALLOUT_TYPES[number];

// ═══════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════

export function generateBlockId(): string {
  return `blk-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export function generatePageId(): string {
  return `pg-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export function normalizePageName(title: string): string {
  return title.toLowerCase().trim();
}

export function createEmptyBlock(
  pageId: string,
  parentId: string | null = null,
  order: string = 'a0',
  type: BlockType = 'paragraph',
): NoteBlock {
  const now = Date.now();
  return {
    id: generateBlockId(),
    type,
    content: '',
    parentId,
    pageId,
    order,
    collapsed: false,
    indent: parentId ? 1 : 0,
    properties: {},
    refs: [],
    createdAt: now,
    updatedAt: now,
  };
}

export function createNewPage(title: string, isJournal: boolean = false, journalDate?: string): NotePage {
  const now = Date.now();
  return {
    id: generatePageId(),
    title,
    name: normalizePageName(title),
    isJournal,
    journalDate,
    properties: {},
    tags: [],
    favorite: false,
    pinned: false,
    createdAt: now,
    updatedAt: now,
  };
}

export function getTodayJournalDate(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

export function formatJournalDate(dateStr: string): string {
  const d = new Date(dateStr + 'T00:00:00');
  return d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
}

export function extractPageLinks(content: string): string[] {
  const regex = /\[\[([^\]]+)\]\]/g;
  const links: string[] = [];
  let match;
  while ((match = regex.exec(content)) !== null) {
    links.push(match[1]);
  }
  return links;
}

export function orderBetween(before: string | null, after: string | null): string {
  if (!before && !after) return 'a0';
  if (!before) return 'a0';
  if (!after) {
    const last = before.charCodeAt(before.length - 1);
    if (last < 122) return before.slice(0, -1) + String.fromCharCode(last + 1);
    return before + '0';
  }
  return before + '5';
}

// ── Block type display helpers ──

export function blockTypeIcon(type: BlockType): string {
  switch (type) {
    case 'heading': return 'heading';
    case 'code': return 'code';
    case 'math': return 'sigma';
    case 'quote': return 'quote';
    case 'callout': return 'alert-circle';
    case 'list-item': return 'list';
    case 'numbered-item': return 'list-ordered';
    case 'todo': return 'check-square';
    case 'divider': return 'minus';
    case 'image': return 'image';
    case 'table': return 'table';
    case 'embed': return 'frame';
    case 'toggle': return 'chevron-right';
    default: return 'type';
  }
}

// Migrate old blocks without type field
export function migrateBlock(block: any): NoteBlock {
  if (!block.type) {
    // Detect type from content
    if (block.content?.startsWith('# ')) return { ...block, type: 'heading', properties: { ...block.properties, level: '1' } };
    if (block.content?.startsWith('## ')) return { ...block, type: 'heading', properties: { ...block.properties, level: '2' } };
    if (block.content?.startsWith('### ')) return { ...block, type: 'heading', properties: { ...block.properties, level: '3' } };
    if (block.content?.startsWith('- [ ] ') || block.content?.startsWith('- [x] ')) return { ...block, type: 'todo' };
    if (block.content?.startsWith('- ')) return { ...block, type: 'list-item' };
    if (block.content?.startsWith('> ')) return { ...block, type: 'quote' };
    if (block.content?.startsWith('---')) return { ...block, type: 'divider' };
    if (block.content?.startsWith('```')) return { ...block, type: 'code' };
    return { ...block, type: 'paragraph' };
  }
  return block;
}
