'use client';

// Block-based note system inspired by Logseq
// Simplified for TypeScript/React implementation

// ── Fractional indexing for block ordering ──
// Uses simple string-based ordering (a, b, c... or a0, a1, b0...)

export interface NoteBlock {
  id: string;
  content: string;           // Markdown text content
  parentId: string | null;   // null = top-level block
  pageId: string;            // Which page this block belongs to
  order: string;             // Fractional index string for ordering
  collapsed: boolean;
  indent: number;            // Nesting depth (0 = top level)
  properties: Record<string, string>; // Block properties like priority::, status::
  refs: string[];            // Page IDs referenced via [[links]]
  createdAt: number;
  updatedAt: number;
}

export interface NotePage {
  id: string;
  title: string;             // Display title
  name: string;              // Lowercase normalized (for lookups)
  isJournal: boolean;
  journalDate?: string;      // YYYY-MM-DD for journal pages
  icon?: string;             // Emoji or icon key
  properties: Record<string, string>;
  tags: string[];
  favorite: boolean;
  pinned: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface NoteBook {
  id: string;
  title: string;
  description?: string;
  pageIds: string[];         // Pages in this book
  icon?: string;
  coverColor?: string;       // Brand color for cover
  createdAt: number;
  updatedAt: number;
  autoGenerated: boolean;    // AI-created from research
  category?: string;         // Topic category
  chapters: NoteBookChapter[];
}

export interface NoteBookChapter {
  id: string;
  title: string;
  pageIds: string[];
  order: number;
}

// Bi-directional link
export interface PageLink {
  sourcePageId: string;
  targetPageId: string;
  sourceBlockId: string;
  context: string;           // Surrounding text for preview
}

// Graph node for visualization
export interface GraphNode {
  id: string;
  label: string;
  size: number;              // Based on link count
  color?: string;
  isJournal: boolean;
}

export interface GraphEdge {
  source: string;
  target: string;
  weight: number;
}

// Search result
export interface NoteSearchResult {
  type: 'page' | 'block';
  pageId: string;
  blockId?: string;
  title: string;
  snippet: string;
  score: number;
}

// AI note generation state
export interface NoteAIState {
  isGenerating: boolean;
  targetPageId: string | null;
  targetBlockId: string | null;
  generatedText: string;
  prompt: string;
}

// Slash command
export interface SlashCommand {
  id: string;
  label: string;
  icon: string;
  description: string;
  category: 'insert' | 'format' | 'embed' | 'ai';
  action: string;            // Action identifier
}

// Default slash commands
export const SLASH_COMMANDS: SlashCommand[] = [
  { id: 'h1', label: 'Heading 1', icon: 'heading-1', description: 'Large section heading', category: 'format', action: 'heading-1' },
  { id: 'h2', label: 'Heading 2', icon: 'heading-2', description: 'Medium section heading', category: 'format', action: 'heading-2' },
  { id: 'h3', label: 'Heading 3', icon: 'heading-3', description: 'Small section heading', category: 'format', action: 'heading-3' },
  { id: 'todo', label: 'To-do', icon: 'check-square', description: 'Task checkbox', category: 'insert', action: 'todo' },
  { id: 'bullet', label: 'Bullet list', icon: 'list', description: 'Simple bullet point', category: 'insert', action: 'bullet' },
  { id: 'numbered', label: 'Numbered list', icon: 'list-ordered', description: 'Numbered item', category: 'insert', action: 'numbered' },
  { id: 'quote', label: 'Quote', icon: 'quote', description: 'Block quote', category: 'format', action: 'quote' },
  { id: 'code', label: 'Code block', icon: 'code', description: 'Fenced code block', category: 'insert', action: 'code' },
  { id: 'divider', label: 'Divider', icon: 'minus', description: 'Horizontal rule', category: 'insert', action: 'divider' },
  { id: 'link', label: 'Page link', icon: 'link', description: 'Link to another page [[...]]', category: 'insert', action: 'page-link' },
  { id: 'embed', label: 'Embed page', icon: 'frame', description: 'Embed another page inline', category: 'embed', action: 'embed-page' },
  { id: 'ai-continue', label: 'AI Continue', icon: 'sparkles', description: 'AI continues writing from here', category: 'ai', action: 'ai-continue' },
  { id: 'ai-summarize', label: 'AI Summarize', icon: 'book-open', description: 'AI summarizes this page', category: 'ai', action: 'ai-summarize' },
  { id: 'ai-expand', label: 'AI Expand', icon: 'expand', description: 'AI expands on this block', category: 'ai', action: 'ai-expand' },
  { id: 'ai-rewrite', label: 'AI Rewrite', icon: 'pen-line', description: 'AI rewrites this block', category: 'ai', action: 'ai-rewrite' },
];

// Helper: generate block ID
export function generateBlockId(): string {
  return `blk-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

// Helper: generate page ID
export function generatePageId(): string {
  return `pg-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

// Helper: normalize page name (for lookups)
export function normalizePageName(title: string): string {
  return title.toLowerCase().trim();
}

// Helper: create empty block
export function createEmptyBlock(pageId: string, parentId: string | null = null, order: string = 'a0'): NoteBlock {
  const now = Date.now();
  return {
    id: generateBlockId(),
    content: '',
    parentId,
    pageId,
    order,
    collapsed: false,
    indent: parentId ? 1 : 0,
    properties: {},
    refs: [],
    createdAt: now,
    updatedAt: now,
  };
}

// Helper: create new page
export function createNewPage(title: string, isJournal: boolean = false, journalDate?: string): NotePage {
  const now = Date.now();
  return {
    id: generatePageId(),
    title,
    name: normalizePageName(title),
    isJournal,
    journalDate,
    properties: {},
    tags: [],
    favorite: false,
    pinned: false,
    createdAt: now,
    updatedAt: now,
  };
}

// Helper: get today's journal date
export function getTodayJournalDate(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

// Helper: format journal date for display
export function formatJournalDate(dateStr: string): string {
  const d = new Date(dateStr + 'T00:00:00');
  return d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
}

// Helper: extract [[page links]] from content
export function extractPageLinks(content: string): string[] {
  const regex = /\[\[([^\]]+)\]\]/g;
  const links: string[] = [];
  let match;
  while ((match = regex.exec(content)) !== null) {
    links.push(match[1]);
  }
  return links;
}

// Helper: generate fractional order between two values
export function orderBetween(before: string | null, after: string | null): string {
  if (!before && !after) return 'a0';
  if (!before) return 'a0';  // Before everything
  if (!after) {
    // After everything — increment last char
    const last = before.charCodeAt(before.length - 1);
    if (last < 122) return before.slice(0, -1) + String.fromCharCode(last + 1);
    return before + '0';
  }
  // Between two values
  return before + '5';  // Simple midpoint
}
