// ═══════════════════════════════════════════════════════════════════
// Suite Architecture — 3-Tier System
// ═══════════════════════════════════════════════════════════════════

import type { InferenceMode } from '@/lib/engine/llm/config';

/**
 * Three suite tiers, ontologically separated by device capability:
 *
 * 'notes'        → Phones, tablets, weak laptops. AI chat + notes + research library.
 *                   No heavy computation. Minimal memory footprint.
 *
 * 'programming'  → Desktops, dev machines. Adds code analysis, language tools,
 *                   codebase suggestions, steering lab.
 *
 * 'full'         → GPU machines, power users. Adds pipeline measurement, TDA,
 *                   signal diagnostics, cortex archive, live controls.
 */
export type SuiteTier = 'notes' | 'programming' | 'full';

/** Legacy alias — kept for migration */
type SuiteMode = SuiteTier;

/** Research chat mode toggle */
export type ChatViewMode = 'chat' | 'visualize-thought';

/** Thinking playback state */
type ThinkingPlayState = 'playing' | 'paused' | 'stopped';

/** Thinking speed multiplier */
type ThinkingSpeed = 0.25 | 0.5 | 1 | 1.5 | 2;

// ═══════════════════════════════════════════════════════════════════
// Research Types
// ═══════════════════════════════════════════════════════════════════

/** A saved research article / paper reference */
export interface ResearchPaper {
  id: string;
  title: string;
  authors: string[];
  year: number;
  journal?: string;
  doi?: string;
  url?: string;
  abstract?: string;
  tags: string[];
  savedAt: number;
  sourceMessageId?: string;
  notes?: string;
}

/** A citation extracted from model output */
export interface Citation {
  id: string;
  text: string;
  source: string;
  authors?: string[];
  year?: number;
  doi?: string;
  url?: string;
  confidence: number;
}

/** A research book — auto-categorized collection of papers */
export interface ResearchBook {
  id: string;
  title: string;
  description?: string;
  coverColor: string;       // Brand color key: 'pfc-violet' | 'pfc-green' | 'pfc-ember' | 'pfc-cyan' | 'pfc-yellow'
  chapters: ResearchBookChapter[];
  paperIds: string[];        // All paper IDs across all chapters
  tags: string[];
  autoGenerated: boolean;    // AI-created from research patterns
  category?: string;         // Topic category (e.g., 'neuroscience', 'methodology')
  createdAt: number;
  updatedAt: number;
}

/** A chapter within a research book */
export interface ResearchBookChapter {
  id: string;
  title: string;
  description?: string;
  paperIds: string[];        // Papers in this chapter
  order: number;             // Sort order
}

/** Thought node for mind-map visualization */
export interface ThoughtNode {
  id: string;
  label: string;
  type: 'query' | 'reasoning' | 'evidence' | 'conclusion' | 'counter' | 'branch';
  parentId?: string;
  children: string[];
  depth: number;
  confidence?: number;
  detail?: string;
}

/** Thought graph for visualization */
export interface ThoughtGraph {
  nodes: ThoughtNode[];
  edges: { from: string; to: string; label?: string; weight?: number }[];
  rootId: string;
}

/** Export format options */
export type ExportFormat = 'json' | 'csv' | 'markdown' | 'bibtex' | 'ris';

/** Export data type */
export type ExportDataType = 'signals' | 'papers' | 'pipeline-runs' | 'thought-graphs' | 'chat-history' | 'all';

/** Educational tooltip entry */
export interface EducationalTooltip {
  id: string;
  title: string;
  description: string;
  useCases: string[];
  learnMore?: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

/** Rerouting instruction for thinking */
export interface RerouteInstruction {
  type: 'focus' | 'explore' | 'challenge' | 'synthesize' | 'simplify';
  detail?: string;
}

// ═══════════════════════════════════════════════════════════════════
// Inference-Mode Feature Gating
// ═══════════════════════════════════════════════════════════════════

/** Which features are available per inference mode */
interface InferenceModeFeatures {
  playPause: boolean;
  speedControl: boolean;
  stopThinking: boolean;
  rerouteThinking: boolean;
  deepResearch: boolean;
  modeLabel: string;
  modeHint: string;
}

/** Get available features for the current inference mode */
export function getInferenceModeFeatures(mode: InferenceMode): InferenceModeFeatures {
  switch (mode) {
    case 'local':
      return {
        playPause: true,
        speedControl: true,
        stopThinking: true,
        rerouteThinking: true,
        deepResearch: true,
        modeLabel: 'Local',
        modeHint: 'Full thinking controls — running on your hardware',
      };
    case 'api':
      return {
        playPause: false,
        speedControl: false,
        stopThinking: true,
        rerouteThinking: true,
        deepResearch: true,
        modeLabel: 'API',
        modeHint: 'Research & notes focused — some controls need local models',
      };
    case 'simulation':
    default:
      return {
        playPause: false,
        speedControl: false,
        stopThinking: true,
        rerouteThinking: true,
        deepResearch: false,
        modeLabel: 'Simulation',
        modeHint: 'Simulated inference — connect a model for full features',
      };
  }
}

// ═══════════════════════════════════════════════════════════════════
// Suite Tier Feature Matrix
// ═══════════════════════════════════════════════════════════════════

/** Complete feature availability for a suite tier */
export interface SuiteTierFeatures {
  // Core (always on)
  chat: boolean;
  researchLibrary: boolean;
  citations: boolean;
  dataExport: boolean;
  educationalTooltips: boolean;

  // Research-level
  thoughtVisualizer: 'off' | 'simplified' | 'full';
  researchMode: boolean;
  deepResearch: boolean;

  // Programming-level
  steeringLab: boolean;

  // Measurement-level
  pipelineVisualizer: boolean;
  signalDiagnostics: boolean;
  tdaTopology: boolean;
  liveControls: boolean;
  cortexArchive: boolean;
  conceptHierarchy: boolean;
  signalOverrides: boolean;

  // Meta
  tierLabel: string;
  tierDescription: string;
  tierColor: string;
}

/** Get feature set for a suite tier */
export function getSuiteTierFeatures(tier: SuiteTier): SuiteTierFeatures {
  switch (tier) {
    case 'notes':
      return {
        chat: true,
        researchLibrary: true,
        citations: true,
        dataExport: true,
        educationalTooltips: true,
        thoughtVisualizer: 'simplified',
        researchMode: true,
        deepResearch: false,
        steeringLab: false,
        pipelineVisualizer: false,
        signalDiagnostics: false,
        tdaTopology: false,
        liveControls: false,
        cortexArchive: false,
        conceptHierarchy: false,
        signalOverrides: false,
        tierLabel: 'Notes & Research',
        tierDescription: 'AI chat, research library, notes, and citations. Optimized for mobile and low-power devices.',
        tierColor: 'pfc-green',
      };
    case 'programming':
      return {
        chat: true,
        researchLibrary: true,
        citations: true,
        dataExport: true,
        educationalTooltips: true,
        thoughtVisualizer: 'full',
        researchMode: true,
        deepResearch: true,
        steeringLab: true,
        pipelineVisualizer: false,
        signalDiagnostics: false,
        tdaTopology: false,
        liveControls: false,
        cortexArchive: false,
        conceptHierarchy: false,
        signalOverrides: false,
        tierLabel: 'Programming Suite',
        tierDescription: 'Research + code analysis, language tools, codebase suggestions, and AI steering.',
        tierColor: 'pfc-violet',
      };
    case 'full':
    default:
      return {
        chat: true,
        researchLibrary: true,
        citations: true,
        dataExport: true,
        educationalTooltips: true,
        thoughtVisualizer: 'full',
        researchMode: true,
        deepResearch: true,
        steeringLab: true,
        pipelineVisualizer: true,
        signalDiagnostics: true,
        tdaTopology: true,
        liveControls: true,
        cortexArchive: true,
        conceptHierarchy: true,
        signalOverrides: true,
        tierLabel: 'Full Measurement',
        tierDescription: 'Everything — pipeline analysis, signal diagnostics, TDA topology, cortex archive.',
        tierColor: 'pfc-ember',
      };
  }
}
