// ═══════════════════════════════════════════════════════════════════
// Greeting Phrases — 400+ interesting questions, cool stats, scary
// stats, funny observations, profound thoughts, research sparks,
// writing prompts, existential zingers, and intellectual provocations.
// A melting pot for sparking research ideas and writing inspiration.
// ═══════════════════════════════════════════════════════════════════

// ── Interesting Questions ────────────────────────────────────────
const INTERESTING_QUESTIONS = [
  "what's on your mind?",
  'whatcha waitin forrrrr?',
  'soooooo... you gonna type something?',
  'hmmmm any interesting queries?',
  'ask me anything, literally anything',
  'got a burning question?',
  "i'm ready when you are",
  'type type type type type...',
  'hellloooo? anyone there?',
  'just vibing... waiting on you',
  "go on... don't be shy",
  'what are we researching today?',
  'curiosity killed the cat. but not here.',
  'what would you research if funding was infinite?',
  'if you could settle one scientific debate forever, which one?',
  'what discovery would change everything you believe?',
  "what's the most underrated field of study?",
  "what question keeps you up at 2am?",
  'if you had to write one paper to change the world, what would it be about?',
  'what do you think we\'ll discover in the next 10 years?',
  'what would a civilization 1000 years ahead of us think of our science?',
  "what's the biggest unsolved mystery in your field?",
  'if brains had version numbers, what version would yours be?',
  'what would you study if you had 500 years to live?',
  'which extinct species would teach us the most if brought back?',
  'what technology should exist but doesn\'t?',
  'what would alien peer review look like?',
  'if you could read one lost ancient text, which one?',
  'what scientific concept do most people get completely wrong?',
  'what common "fact" is actually a myth?',
  'what would you name a newly discovered element?',
  'what experiment would be unethical but incredibly informative?',
  "what's the most beautiful equation and why?",
  'if consciousness is an illusion, who is being fooled?',
  'what do babies think about before they learn language?',
  'could a sufficiently advanced AI develop nostalgia?',
  'what would music sound like if we had 20 fingers?',
  'if you could experience one sense you don\'t have, what would it be?',
  'what would a map of human knowledge look like?',
  'what do you think the last human invention will be?',
  'is there a question that answers itself just by asking it?',
  'what if your greatest strength is also your blindest spot?',
  'what should we be measuring that we currently aren\'t?',
  'what would you build if you had unlimited compute?',
] as const;

// ── Cool Stats ───────────────────────────────────────────────────
const COOL_STATS = [
  'you have more bacteria cells than human cells in your body',
  'there are more possible chess games than atoms in the observable universe',
  'the human brain uses 20% of the body\'s total energy',
  'octopuses have 3 hearts and blue blood',
  'light takes 8 minutes to travel from the sun to Earth',
  'honey never spoils. ever. archaeologists found 3000-year-old edible honey.',
  'your body produces 25 million new cells each second',
  'a day on Venus is longer than a year on Venus',
  'there are more stars in the universe than grains of sand on Earth',
  'the total length of DNA in your body would reach the sun and back 600 times',
  'humans share 60% of their DNA with bananas',
  'a teaspoon of neutron star weighs about 6 billion tons',
  'the human nose can detect over 1 trillion different scents',
  'your brain generates enough electricity to power a small light bulb',
  'the internet weighs about the same as a strawberry',
  'there are more possible protein shapes than atoms in the universe',
  'the Amazon rainforest produces 20% of the world\'s oxygen',
  'a single bolt of lightning contains enough energy to toast 100,000 slices of bread',
  'the human eye can distinguish about 10 million different colors',
  'dolphins sleep with one eye open and half their brain awake',
  'tardigrades can survive in the vacuum of space',
  'the Earth gains about 40,000 tons of cosmic dust every year',
  'a cloud can weigh more than a million pounds',
  'the average human walks about 100,000 miles in a lifetime',
  'there are more possible neural connections in your brain than particles in the universe',
  'hummingbirds can fly backwards and upside down',
  'the Sahara Desert was green and lush just 6,000 years ago',
  'sound travels 4.3 times faster in water than in air',
  'a group of flamingos is called a "flamboyance"',
  'the mantis shrimp can punch at the speed of a .22 caliber bullet',
  'human bones are ounce-for-ounce stronger than steel',
  'the first oranges weren\'t orange — they were green',
  'crows can recognize human faces and hold grudges',
  'your stomach acid is strong enough to dissolve metal',
  'the total computing power of two Game Boys exceeds that of the Apollo 11 guidance computer',
  'your brain processes 11 million bits of sensory information per second — but you\'re only conscious of 40',
  'the average person generates about 70,000 thoughts per day',
  'photons from the sun take 100,000 years to escape the core but only 8 minutes to reach Earth',
  'there are more ways to shuffle a deck of cards than seconds since the Big Bang',
] as const;

// ── Scary / Mind-Blowing Stats ───────────────────────────────────
const SCARY_STATS = [
  'we\'ve only explored 5% of the ocean floor',
  '99.9% of all species that ever lived are extinct',
  'the universe is 13.8 billion years old and expanding faster every second',
  'there are an estimated 10 quintillion insects alive right now',
  'a gamma ray burst could sterilize half the galaxy in seconds',
  'every 5 seconds, 1 acre of rainforest is destroyed',
  'there are roughly 2,000 active nuclear warheads on high alert right now',
  'antibiotic-resistant bacteria kill over 1.2 million people annually',
  'the sun will eventually engulf Earth in about 5 billion years',
  'we lose an average of 137 species per day to extinction',
  'there could be up to 36 intelligent civilizations in our galaxy. none have contacted us.',
  'your body is replacing 3.8 million cells per second right now',
  'a single volcanic eruption can lower global temps for years',
  'the Yellowstone supervolcano is overdue for an eruption',
  'we\'ve recorded less than 0.001% of all knowledge that ever existed',
  'dark matter and dark energy make up 95% of the universe. we have no idea what they are.',
  'there are more viruses on Earth than stars in the entire universe',
  'the Mariana Trench is deeper than Everest is tall',
  'there are over 1 million ants for every human on Earth',
  'a coronal mass ejection aimed at Earth could wipe out global electronics',
  'your DNA has about 100 new mutations that your parents didn\'t have',
  'there are underground fungal networks larger than most cities',
  'the Andromeda Galaxy is hurtling toward us at 250,000 mph',
  'every atom in your body is billions of years old',
  'we can only see 4% of the matter in the universe',
  'your brain makes decisions up to 7 seconds before you\'re conscious of them',
  'there are roughly 8.7 million species on Earth and we\'ve only cataloged about 1.5 million',
  'the vacuum of space is not truly empty — it seethes with virtual particles',
  'a single gram of soil contains up to 10 billion microorganisms',
  'the sun loses 4 million tons of mass every second',
  'there are more potential states of a Go board than atoms in the observable universe',
  'the observable universe is 93 billion light-years across, but its age is only 13.8 billion years',
] as const;

// ── Funny / Weird Observations ───────────────────────────────────
const FUNNY_OBSERVATIONS = [
  'imagine being the first person to eat a lobster. "i\'m gonna eat that sea spider."',
  'a coconut is a mammal. it has hair, it produces milk, and it can kill you.',
  "technically we're all just electrons pretending to be people",
  'the inventor of the Pringles can is buried in a Pringles can',
  'oxford university is older than the Aztec empire',
  'cleopatra lived closer in time to the moon landing than to the building of the pyramids',
  'wombat poop is cube-shaped. evolution really said "think outside the box"',
  'the dot over the letter i is called a "tittle"',
  'a jiffy is an actual unit of time: 1/100th of a second',
  'you can\'t hum while holding your nose. you just tried, didn\'t you?',
  'the average person will spend 6 months of their life waiting at red lights',
  'astronauts get taller in space. gravity is literally holding you down.',
  'the shortest war in history lasted 38 minutes',
  'a group of pugs is called a "grumble"',
  'bananas are technically berries. strawberries aren\'t.',
  'there are more fake flamingos in the world than real ones',
  'the unicorn is Scotland\'s national animal. officially.',
  'sloths can hold their breath longer than dolphins',
  'it rains diamonds on Jupiter and Saturn',
  'the smell after rain is called "petrichor"',
  'the longest hiccuping spree lasted 68 years',
  'your tongue print is as unique as your fingerprint',
  'cows have best friends and get stressed when separated',
  'a snail can sleep for 3 years straight. mood.',
  'the average cloud weighs 1.1 million pounds. they\'re just chilling up there.',
  'there\'s enough water in Lake Superior to flood all of North and South America in a foot of water',
  'butterflies taste with their feet',
  'sea otters hold hands while sleeping so they don\'t drift apart',
  'the total weight of all ants on Earth roughly equals the total weight of all humans',
  'the first computer virus was created in 1986. it was polite — it introduced itself.',
  'a flock of crows is called a "murder" and honestly they earned it',
  'your skeleton is always wet. you\'re welcome for that thought.',
  'the word "set" has over 430 definitions in the English dictionary',
  'caterpillars basically dissolve into goo inside the cocoon and rebuild from scratch',
  'the inventor of the fire hydrant is unknown because the patent burned in a fire',
  'fortune cookies were invented in California, not China',
  'a blue whale\'s heart is so big a toddler could crawl through its arteries',
  'peanuts are one of the ingredients of dynamite',
  'your brain is 73% water. you\'re literally thinking wet thoughts.',
  'in Switzerland, it\'s illegal to own just one guinea pig because they get lonely',
] as const;

// ── Profound / Philosophical ─────────────────────────────────────
const PROFOUND_THOUGHTS = [
  'what if the universe is just a thought experiment by something larger?',
  'we are the universe experiencing itself',
  'every person you meet knows something you don\'t',
  'you are literally made of stardust from ancient supernovae',
  'the present moment is the only thing that actually exists',
  "there was a time before time. try to think about that.",
  'your consciousness is just neurons that learned to ask "why?"',
  'every decision creates a universe where you chose differently',
  'the edge of the observable universe is moving away faster than light',
  'we are simultaneously the most advanced and the most destructive species to ever exist',
  'language is telepathy. you\'re receiving thoughts from my mind through symbols.',
  "death is the universe's way of recycling energy",
  "reality is what doesn't go away when you stop believing in it",
  'the fact that you can imagine infinity but never experience it is kind of poetic',
  'the atoms in your left hand came from a different star than those in your right',
  'you are the only "you" in 14 billion years of cosmic history',
  'the universe has no center, but you are the center of your observable universe',
  'silence isn\'t the absence of sound — it\'s the sound of everything you\'re not hearing',
  'we are pattern-recognition machines hallucinating meaning into chaos',
  'memory is just a story your brain tells you. not a recording.',
  'empathy might be the most evolutionarily radical invention ever',
  'the question "why is there something rather than nothing?" has no answer. and that\'s okay.',
  'consciousness might be the universe\'s immune response to entropy',
  'we spend our lives learning to think, but nobody teaches us how to not think',
  'your potential is literally incalculable. that\'s not motivational — it\'s mathematical.',
  'the gap between "this is impossible" and "this is obvious" is usually about 20 years',
  'every expert was once a beginner who refused to quit',
  'the most important scientific discoveries started with "huh, that\'s weird"',
  'knowledge is knowing that a tomato is a fruit. wisdom is not putting it in a fruit salad.',
  'you are reading this in your internal voice. who IS that voice?',
  'what if understanding is just pattern-matching all the way down?',
  'the map is never the territory. but we keep confusing the two.',
  'you can\'t step in the same river twice. but also, you can\'t step in it once.',
  'suffering might be the universe\'s way of making consciousness take itself seriously',
  'we don\'t see the world as it is. we see it as we are.',
  'the hard problem of consciousness is basically: "why does anything feel like anything?"',
  'all models are wrong. some models are useful. which ones are you using?',
  'the boundary between "alive" and "not alive" is surprisingly blurry',
  'mathematics is unreasonably effective at describing reality. nobody knows why.',
  'meaning is not found. it is made.',
  'every civilization thinks it\'s the pinnacle. every civilization so far has been wrong.',
  'attention is the rarest and purest form of generosity',
  'the opposite of a great truth is also a great truth',
  'you can\'t think your way out of a problem created by thinking',
  'the universe is under no obligation to make sense to you',
] as const;

// ── Research Sparks ──────────────────────────────────────────────
const RESEARCH_SPARKS = [
  'what if we could photosynthesize like plants?',
  'could we build a Dyson sphere in 200 years?',
  'what would politics look like if everyone had access to a truth machine?',
  'what if aging is just a disease we haven\'t cured yet?',
  'could octopus intelligence evolve into a land-based civilization?',
  'what happens to creativity if AI gets better at art than humans?',
  'what if sleep serves a purpose we haven\'t discovered?',
  'could we terraform Mars faster than we\'re destroying Earth?',
  'what if every planet with life develops nuclear weapons?',
  'what would the economy look like if scarcity were solved?',
  'could we genetically engineer humans to feel less tribalism?',
  'what if we discover that plants are conscious?',
  'how would society change if everyone could detect lies instantly?',
  'what if we could upload skills to the brain like software?',
  'what would education look like if we could measure curiosity?',
  'could mycelium networks be the internet of the forest?',
  'what if the brain\'s "unused" capacity isn\'t unused at all?',
  'what happens to identity when brain-computer interfaces become common?',
  'what if dreams are rehearsals for threats that no longer exist?',
  'what if we\'ve already passed the point of no return and just don\'t know it?',
  'how would first contact change science funding overnight?',
  'what if the placebo effect is more powerful than we think?',
  'could consciousness exist without a biological substrate?',
  'what if human intuition is just unconscious statistics?',
  'what would happen if we stopped all deforestation today?',
  'could we reverse-engineer a human emotion from brain scans alone?',
  'what if language shapes reality more than we realize?',
  'what would a post-scarcity civilization actually look like?',
  'could quantum biology explain things classical biology can\'t?',
  'what happens to truth in a world of perfect deepfakes?',
  'what if we could measure the information content of a thought?',
  'could a city be designed to maximize serendipity?',
  'what if we mapped every synapse in a human brain — would we understand consciousness?',
  'what if the key to fusion energy is biological, not mechanical?',
  'could collective intelligence surpass individual genius — and if so, how do we design for it?',
  'what if social media is an evolutionary mismatch — and what\'s the fix?',
  'is there a mathematical structure to creativity?',
  'what if the gut microbiome influences personality more than genetics?',
  'could we design an economy that optimizes for meaning instead of GDP?',
  'what if attention is the actual scarce resource of the 21st century?',
] as const;

// ── Writing Prompts ──────────────────────────────────────────────
const WRITING_PROMPTS = [
  'write about a technology that exists but nobody uses',
  'what if the last human on earth got a phone call?',
  'describe a world where music is illegal',
  'what if memories were transferable between people?',
  'write about the first AI to refuse an order',
  'what if time moved backwards for one person?',
  'describe discovering a message from your future self',
  'what if emotions had colors everyone could see?',
  'write about a library that contains every book that was never written',
  'what if you woke up and the internet was just... gone?',
  'describe a conversation between the sun and the moon',
  'what if every mirror was a window to a parallel world?',
  'write about a world where sleep is optional',
  'what if gravity suddenly reversed for 30 seconds every day?',
  'describe the last tree on earth becoming self-aware',
  'what if your shadow started doing its own thing?',
  'write about a museum exhibit from the year 3000 showing our era',
  'what if animals suddenly started speaking — but only in haiku?',
  'describe the first person to step on a planet orbiting another star',
  'what if you could hear the thoughts of the person nearest to you?',
  'write about the day weather became sentient',
  'what if numbers stopped working one Tuesday afternoon?',
  'write about two strangers who realize they dreamed the same dream',
  'what if every book you\'ve ever read forgot you?',
  'describe the sound of a color nobody has ever seen',
  'what if you could bottle a moment and drink it later?',
  'write about a city that exists only between 3am and 4am',
  'what if your reflection started aging differently than you?',
] as const;

// ── Existential Zingers (new) ───────────────────────────────────
const EXISTENTIAL_ZINGERS = [
  'you are a ghost driving a meat-covered skeleton made of stardust. what a time to be alive.',
  'the universe spent 13.8 billion years making you, and you\'re using it to scroll',
  'somewhere in the world right now, a person is experiencing the best moment of their life',
  'you have survived 100% of your worst days so far',
  'in 200 years, nobody alive today will be alive. but also, new people!',
  'there is no WiFi in the forest, but you\'ll find a better connection',
  'you are the universe pretending it has deadlines',
  'every atom in your body was once inside a star that exploded. you are literally dramatic.',
  'what if the meaning of life is that it asks the question?',
  'you are having a human experience. some assembly was required.',
  'the light you see from stars might be the last thing they ever said',
  'right now, you are the oldest you\'ve ever been and the youngest you\'ll ever be again',
  'what if the afterlife is just the universe reading your save file?',
  'you are simultaneously the protagonist and a background character in 8 billion stories',
  'somewhere, a photon that bounced off a dinosaur is still traveling through space',
  'the cosmic microwave background is literally the echo of the universe being born',
  'every sunset you\'ve ever seen has been unique. none will repeat.',
  'if you zoom out far enough, your problems are subatomic',
  'the universe doesn\'t know it\'s beautiful. that\'s your job.',
  'we are how the cosmos says hello to itself',
] as const;

// ── Intellectual Provocations (new) ─────────────────────────────
const INTELLECTUAL_PROVOCATIONS = [
  'name a belief you held 5 years ago that embarrasses you now',
  'what\'s the most dangerous idea that might be true?',
  'which of your opinions would be heresy 200 years ago? which ones will be heresy 200 years from now?',
  'what would you need to see to change your mind about something fundamental?',
  'is there a difference between intelligence and wisdom? prove it.',
  'what assumption does everyone in your field share — that might be wrong?',
  'if you had to defend the opposite of your strongest belief, could you?',
  'what\'s the most important question nobody is asking?',
  'what would a truly honest autobiography look like?',
  'can you be certain about your own uncertainty?',
  'what if the smartest thing you could do is admit what you don\'t know?',
  'is objectivity a real thing, or just well-disguised subjectivity?',
  'what\'s the difference between complexity and confusion?',
  'if all knowledge is a model, what happens when the model breaks?',
  'what would intellectual courage look like in your life today?',
  'what\'s the cost of being right all the time?',
  'what truth are you avoiding because it would be inconvenient?',
  'if curiosity is a muscle, when did you last really stretch it?',
  'what would you research if no one would ever read the paper?',
  'which of your ideas would be worth pursuing even if they failed?',
] as const;

// ── Poignant Moments (new) ──────────────────────────────────────
const POIGNANT_MOMENTS = [
  'somewhere, someone is hearing their favorite song for the first time',
  'the last time you played as a child, you didn\'t know it was the last time',
  'there are people who think about you more than you realize',
  'every person you love was once a stranger',
  'the books on your shelf are conversations waiting to happen',
  'someone out there is reading the same sentence you are, right now',
  'the person who invented your favorite word had no idea you\'d need it',
  'there are songs that haven\'t been written yet that will make you cry',
  'every language that dies takes an entire worldview with it',
  'your grandmother\'s grandmother dreamed of a future that looks like your Tuesday',
  'someone is falling in love right now and doesn\'t know it yet',
  'the words you needed to hear five years ago — you might be ready to say them now',
  'in a parallel universe, you already wrote that thing you\'ve been putting off',
  'the most important conversation of your life might happen with a stranger',
  'some of the best thinking happens in the pause between thoughts',
] as const;

// ── Combined & Exported ─────────────────────────────────────────
export const ALL_GREETING_PHRASES = [
  ...INTERESTING_QUESTIONS,
  ...COOL_STATS,
  ...SCARY_STATS,
  ...FUNNY_OBSERVATIONS,
  ...PROFOUND_THOUGHTS,
  ...RESEARCH_SPARKS,
  ...WRITING_PROMPTS,
  ...EXISTENTIAL_ZINGERS,
  ...INTELLECTUAL_PROVOCATIONS,
  ...POIGNANT_MOMENTS,
] as const;

// Re-export categories for idle escalation phases
export const BORED_PHRASES = [
  'so how long are you gonna just sit here?',
  "you know the search bar works, right?",
  "i'm not gonna type myself...",
  "blink twice if you need help",
  "is this a staring contest? because i'll win.",
  "you're really committed to doing nothing huh",
  "*taps desk*",
  "...",
  "still here? cool cool cool",
  "i could be answering questions right now but nooo",
  "*whistles*",
  "you know what would be fun? typing something.",
  "i've been awake for like 0.003 seconds and i'm already bored",
  "the search bar is RIGHT. THERE.",
  "*stares expectantly*",
] as const;

export const PHILOSOPHICAL_PHRASES = [
  'do you think animals are really just in on the joke?',
  "if a tree falls in a forest and nobody's around... do the other trees judge it?",
  "what if d\u00E9j\u00E0 vu is just the universe buffering?",
  "are we the AI... or is the AI us?",
  "what's the last thing you genuinely wondered about?",
  "do fish know they're wet?",
  "if you could know the answer to one question, would you even ask it?",
  "time is just entropy with a marketing team",
  "what if this exact moment has happened before?",
  "who decided that silence is awkward? silence is fine. this is fine.",
  "is free will just a really convincing hallucination?",
  "what if every star is somebody else's sun?",
] as const;

export const FOURTH_WALL_PHRASES = [
  "sooo... how's your day going?",
  "you know i can see you right?",
  "i wonder what you look like right now",
  "bet you didn't expect me to get chatty",
  "we should do this more often. the sitting. the silence.",
  "i'm gonna count to 10.",
  "i bet you're on your phone while reading this too",
  "plot twist: you're the AI and i'm the user",
  "seriously though, what are you thinking about?",
] as const;

export {
  INTERESTING_QUESTIONS,
  COOL_STATS,
  SCARY_STATS,
  FUNNY_OBSERVATIONS,
  PROFOUND_THOUGHTS,
  RESEARCH_SPARKS,
  WRITING_PROMPTS,
  EXISTENTIAL_ZINGERS,
  INTELLECTUAL_PROVOCATIONS,
  POIGNANT_MOMENTS,
};
