// ═══════════════════════════════════════════════════════════════════
// Suite Architecture — Single Mode (all features enabled)
// ═══════════════════════════════════════════════════════════════════

import type { InferenceMode } from '@/lib/engine/llm/config';

/**
 * Single mode — all features always enabled.
 * Kept as a type for backward compatibility with store/localStorage.
 */
export type SuiteTier = 'programming';

/** Research chat mode toggle */
export type ChatViewMode = 'chat' | 'visualize-thought';

/** Thinking playback state */
type ThinkingPlayState = 'playing' | 'paused' | 'stopped';

/** Thinking speed multiplier */
type ThinkingSpeed = 0.25 | 0.5 | 1 | 1.5 | 2;

// ═══════════════════════════════════════════════════════════════════
// Research Types
// ═══════════════════════════════════════════════════════════════════

/** A saved research article / paper reference */
export interface ResearchPaper {
  id: string;
  title: string;
  authors: string[];
  year: number;
  journal?: string;
  doi?: string;
  url?: string;
  abstract?: string;
  tags: string[];
  savedAt: number;
  sourceMessageId?: string;
  notes?: string;
}

/** A citation extracted from model output */
export interface Citation {
  id: string;
  text: string;
  source: string;
  authors?: string[];
  year?: number;
  doi?: string;
  url?: string;
  confidence: number;
}

/** A research book — auto-categorized collection of papers */
export interface ResearchBook {
  id: string;
  title: string;
  description?: string;
  coverColor: string;       // Brand color key: 'pfc-violet' | 'pfc-green' | 'pfc-ember' | 'pfc-cyan' | 'pfc-yellow'
  chapters: ResearchBookChapter[];
  paperIds: string[];        // All paper IDs across all chapters
  tags: string[];
  autoGenerated: boolean;    // AI-created from research patterns
  category?: string;         // Topic category (e.g., 'neuroscience', 'methodology')
  createdAt: number;
  updatedAt: number;
}

/** A chapter within a research book */
export interface ResearchBookChapter {
  id: string;
  title: string;
  description?: string;
  paperIds: string[];        // Papers in this chapter
  order: number;             // Sort order
}

/** Thought node for mind-map visualization */
export interface ThoughtNode {
  id: string;
  label: string;
  type: 'query' | 'reasoning' | 'evidence' | 'conclusion' | 'counter' | 'branch';
  parentId?: string;
  children: string[];
  depth: number;
  confidence?: number;
  detail?: string;
}

/** Thought graph for visualization */
export interface ThoughtGraph {
  nodes: ThoughtNode[];
  edges: { from: string; to: string; label?: string; weight?: number }[];
  rootId: string;
}

/** Export format options */
export type ExportFormat = 'json' | 'csv' | 'markdown' | 'bibtex' | 'ris';

/** Export data type */
export type ExportDataType = 'signals' | 'papers' | 'pipeline-runs' | 'thought-graphs' | 'chat-history' | 'all';

/** Educational tooltip entry */
export interface EducationalTooltip {
  id: string;
  title: string;
  description: string;
  useCases: string[];
  learnMore?: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

/** Rerouting instruction for thinking */
export interface RerouteInstruction {
  type: 'focus' | 'explore' | 'challenge' | 'synthesize' | 'simplify';
  detail?: string;
}

// ═══════════════════════════════════════════════════════════════════
// Inference-Mode Feature Gating
// ═══════════════════════════════════════════════════════════════════

/** Which features are available per inference mode */
interface InferenceModeFeatures {
  playPause: boolean;
  speedControl: boolean;
  stopThinking: boolean;
  rerouteThinking: boolean;
  deepResearch: boolean;
  modeLabel: string;
  modeHint: string;
}

/** Get available features for the current inference mode */
export function getInferenceModeFeatures(mode: InferenceMode): InferenceModeFeatures {
  switch (mode) {
    case 'local':
      return {
        playPause: true,
        speedControl: true,
        stopThinking: true,
        rerouteThinking: true,
        deepResearch: true,
        modeLabel: 'Local',
        modeHint: 'Full thinking controls — running on your hardware',
      };
    case 'api':
    default:
      return {
        playPause: false,
        speedControl: false,
        stopThinking: true,
        rerouteThinking: true,
        deepResearch: true,
        modeLabel: 'API',
        modeHint: 'Research & notes focused — some controls need local models',
      };
  }
}

// ═══════════════════════════════════════════════════════════════════
// Suite Tier Feature Matrix
// ═══════════════════════════════════════════════════════════════════

/** Complete feature availability for a suite tier */
export interface SuiteTierFeatures {
  // Core (always on)
  chat: boolean;
  researchLibrary: boolean;
  citations: boolean;
  dataExport: boolean;
  educationalTooltips: boolean;

  // Research-level
  thoughtVisualizer: 'off' | 'simplified' | 'full';
  researchMode: boolean;
  deepResearch: boolean;

  // Programming-level
  steeringLab: boolean;

  // Measurement-level
  pipelineVisualizer: boolean;
  signalDiagnostics: boolean;
  tdaTopology: boolean;
  liveControls: boolean;
  cortexArchive: boolean;
  conceptHierarchy: boolean;
  signalOverrides: boolean;

  // Meta
  tierLabel: string;
  tierDescription: string;
  tierColor: string;
}

/** Get feature set — single mode, all features enabled */
export function getSuiteTierFeatures(_tier?: SuiteTier): SuiteTierFeatures {
  return {
    chat: true,
    researchLibrary: true,
    citations: true,
    dataExport: true,
    educationalTooltips: true,
    thoughtVisualizer: 'full',
    researchMode: true,
    deepResearch: true,
    steeringLab: true,
    pipelineVisualizer: false,
    signalDiagnostics: true,
    tdaTopology: false,
    liveControls: true,
    cortexArchive: true,
    conceptHierarchy: true,
    signalOverrides: true,
    tierLabel: 'PFC Suite',
    tierDescription: 'Full analysis suite — all features enabled.',
    tierColor: 'pfc-violet',
  };
}
